# Generated by Django 4.1.3 on 2022-11-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(default='UT', max_length=2)),
                ('courts', models.IntegerField(default=0)),
                ('openTime', models.TimeField(default=None)),
                ('closeTime', models.TimeField(default=None)),
                ('indoor', models.BooleanField(default=False)),
            ],
        ),
    ]
